workflows:
  android-app:
    name: Android Calculator App
    max_build_duration: 60
    environment:
      android_signing:
        - keystore_reference
      groups:
        - google_play
      vars:
        JAVA_HOME: $JAVA_HOME
      android_sdk: latest

    scripts:
      - name: Set up local properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"

      - name: Build Android app
        script: |
          ./gradlew assembleRelease

      - name: Run tests
        script: |
          ./gradlew test

    artifacts:
      - app/build/outputs/apk/release/**/*.apk
      - app/build/outputs/mapping/release/mapping.txt

    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: true
          failure: true