android_signing:
  - calculator-release-keystore  # must match what's in Codemagic
      groups:
        - google_play
      vars:
        JAVA_HOME: /opt/java/openjdk17

    scripts:
      - name: Set up local properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"

      - name: Build Android app
        script: |
          ./gradlew assembleRelease

      - name: Run tests
        script: |
          ./gradlew test

      - name: Lint the code
        script: |
          ./gradlew lint

    artifacts:
      - app/build/outputs/apk/release/**/*.apk
      - app/build/outputs/mapping/release/mapping.txt

    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: true
          failure: true

      # Uncomment below to enable Google Play publishing
      # google_play:
      #   track: production
      #   release_status: completed
      #   service_account: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS